name: Build for CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin-ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: dotnet test tests\Plugin.Maui.MessagingCenter.UnitTests.csproj

    - name: Build
      run: dotnet build src\Plugin.Maui.MessagingCenter.sln -c Release
